In [1]:


# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)


[[1 2]
 [3 4]
 [5 6]]


In [3]:
A.shape

(3, 2)

In [4]:
# SVD
U, s, VT = svd(A)
print(U, U.shape)
print(s, s.shape)
print(VT, VT.shape)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] (3, 3)
[9.52551809 0.51430058] (2,)
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]] (2, 2)


In [ ]:
# 
#U (m x m) . Sigma (n x n) . V^T (n x n)


In [5]:

# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))


[[1 2]
 [3 4]
 [5 6]]


In [6]:
Sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)


In [8]:
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [9]:
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
