In [1]:
import pandas as pd 
import numpy as np 

p = [15 , 12,  8,   8,   7,   7,   7,   6,   5,   3]
h = [10 , 25,  17,  11,  13,  17,  20,  13,  9,   15]

phy = np.array(p)
his = np.array(h)


In [2]:
phy

array([15, 12,  8,  8,  7,  7,  7,  6,  5,  3])

In [3]:
his

array([10, 25, 17, 11, 13, 17, 20, 13,  9, 15])

In [4]:
covariance = np.cov(phy, his )

In [5]:
from scipy.stats import pearsonr

In [7]:
corr, _ = pearsonr(phy, his)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: 0.145


In [24]:
from math import ceil
def minSum(num, k):
    # Write your code here
    final_array = []
    for i in num:
        
        
            

In [25]:
minSum([10,20,7], 4)

10
20
7


In [30]:
url  ='https://s3.amazonaws.com/istreet-questions-us-east-1/443606/census.csv'

In [31]:
c=pd.read_csv(url)

In [53]:
df = pd.read_csv(url)

In [32]:
c.head()

age=Middle-aged    sex=Male  education=Bachelors  \
0       age=Senior    sex=Male  education=Bachelors   
1  age=Middle-aged    sex=Male    education=HS-grad   
2       age=Senior    sex=Male       education=11th   
3  age=Middle-aged  sex=Female  education=Bachelors   
4  age=Middle-aged  sex=Female    education=Masters   

   native-country=United-States  race=White  \
0  native-country=United-States  race=White   
1  native-country=United-States  race=White   
2  native-country=United-States  race=Black   
3           native-country=Cuba  race=Black   
4  native-country=United-States  race=White   

        marital-status=Never-married         workclass=State-gov  \
0  marital-status=Married-civ-spouse  workclass=Self-emp-not-inc   
1            marital-status=Divorced           workclass=Private   
2  marital-status=Married-civ-spouse           workclass=Private   
3  marital-status=Married-civ-spouse           workclass=Private   
4  marital-status=Married-civ-spouse           workclass=Private   

        occupation=Adm-clerical  hours-per-week=Full-time  income=Small  \
0    occupation=Exec-managerial  hours-per-week=Part-time  income=Small   
1  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
2  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
3     occupation=Prof-specialty  hours-per-week=Full-time  income=Small   
4    occupation=Exec-managerial  hours-per-week=Full-time  income=Small   

    capital-gain=Low  capital-loss=None  
0  capital-gain=None  capital-loss=None  
1  capital-gain=None  capital-loss=None  
2  capital-gain=None  capital-loss=None  
3  capital-gain=None  capital-loss=None  
4  capital-gain=None  capital-loss=None

In [34]:
c.dtypes

age=Middle-aged                 object
sex=Male                        object
education=Bachelors             object
native-country=United-States    object
race=White                      object
marital-status=Never-married    object
workclass=State-gov             object
occupation=Adm-clerical         object
hours-per-week=Full-time        object
income=Small                    object
capital-gain=Low                object
capital-loss=None               object
dtype: object

In [36]:
c.columns

Index(['age=Middle-aged', 'sex=Male', 'education=Bachelors',
       'native-country=United-States', 'race=White',
       'marital-status=Never-married', 'workclass=State-gov',
       'occupation=Adm-clerical', 'hours-per-week=Full-time', 'income=Small',
       'capital-gain=Low', 'capital-loss=None'],
      dtype='object')

In [37]:
c['age=Middle-aged'].value_counts()

age=Middle-aged    15754
age=Senior          7900
age=Young           5668
age=Old              839
Name: age=Middle-aged, dtype: int64

In [39]:
c['sex=Male'].value_counts()

sex=Male      20379
sex=Female     9782
Name: sex=Male, dtype: int64

In [40]:
c.columns = ['age', 'sex', 'education',
       'native-country', 'race',
       'marital-status', 'workclass',
       'occupation', 'hours-per-week', 'income',
       'capital-gain', 'capital-loss']

In [51]:
c.head()

sex            education                native-country        race  \
0    sex=Male  education=Bachelors  native-country=United-States  race=White   
1    sex=Male    education=HS-grad  native-country=United-States  race=White   
2    sex=Male       education=11th  native-country=United-States  race=Black   
3  sex=Female  education=Bachelors           native-country=Cuba  race=Black   
4  sex=Female    education=Masters  native-country=United-States  race=White   

                      marital-status                   workclass  \
0  marital-status=Married-civ-spouse  workclass=Self-emp-not-inc   
1            marital-status=Divorced           workclass=Private   
2  marital-status=Married-civ-spouse           workclass=Private   
3  marital-status=Married-civ-spouse           workclass=Private   
4  marital-status=Married-civ-spouse           workclass=Private   

                     occupation            hours-per-week        income  \
0    occupation=Exec-managerial  hours-per-week=Part-time  income=Small   
1  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
2  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
3     occupation=Prof-specialty  hours-per-week=Full-time  income=Small   
4    occupation=Exec-managerial  hours-per-week=Full-time  income=Small   

        capital-gain       capital-loss  age_age=Middle-aged  age_age=Old  \
0  capital-gain=None  capital-loss=None                    0            0   
1  capital-gain=None  capital-loss=None                    1            0   
2  capital-gain=None  capital-loss=None                    0            0   
3  capital-gain=None  capital-loss=None                    1            0   
4  capital-gain=None  capital-loss=None                    1            0   

   age_age=Senior  age_age=Young  
0               1              0  
1               0              0  
2               1              0  
3               0              0  
4               0              0

In [50]:
c.head()

sex            education                native-country        race  \
0    sex=Male  education=Bachelors  native-country=United-States  race=White   
1    sex=Male    education=HS-grad  native-country=United-States  race=White   
2    sex=Male       education=11th  native-country=United-States  race=Black   
3  sex=Female  education=Bachelors           native-country=Cuba  race=Black   
4  sex=Female    education=Masters  native-country=United-States  race=White   

                      marital-status                   workclass  \
0  marital-status=Married-civ-spouse  workclass=Self-emp-not-inc   
1            marital-status=Divorced           workclass=Private   
2  marital-status=Married-civ-spouse           workclass=Private   
3  marital-status=Married-civ-spouse           workclass=Private   
4  marital-status=Married-civ-spouse           workclass=Private   

                     occupation            hours-per-week        income  \
0    occupation=Exec-managerial  hours-per-week=Part-time  income=Small   
1  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
2  occupation=Handlers-cleaners  hours-per-week=Full-time  income=Small   
3     occupation=Prof-specialty  hours-per-week=Full-time  income=Small   
4    occupation=Exec-managerial  hours-per-week=Full-time  income=Small   

        capital-gain       capital-loss  age_age=Middle-aged  age_age=Old  \
0  capital-gain=None  capital-loss=None                    0            0   
1  capital-gain=None  capital-loss=None                    1            0   
2  capital-gain=None  capital-loss=None                    0            0   
3  capital-gain=None  capital-loss=None                    1            0   
4  capital-gain=None  capital-loss=None                    1            0   

   age_age=Senior  age_age=Young  
0               1              0  
1               0              0  
2               1              0  
3               0              0  
4               0              0

In [52]:
c.describe()

age_age=Middle-aged   age_age=Old  age_age=Senior  age_age=Young
count         30161.000000  30161.000000    30161.000000   30161.000000
mean              0.522330      0.027817        0.261928       0.187925
std               0.499509      0.164452        0.439691       0.390659
min               0.000000      0.000000        0.000000       0.000000
25%               0.000000      0.000000        0.000000       0.000000
50%               1.000000      0.000000        0.000000       0.000000
75%               1.000000      0.000000        1.000000       0.000000
max               1.000000      1.000000        1.000000       1.000000

In [54]:
import numpy as np 

In [55]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [58]:
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [59]:
np.zeros(4)

array([0., 0., 0., 0.])

In [65]:
s = np.zeros_like(5, order=(5,6) )

In [66]:
s

array(0)

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.ones(1)

array([1.])

In [70]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])